"""
orchestrator/models/summary.py
--------------------------------
SummaryResult dataclass — the canonical output of the LLM fallback chain.

New schema (enterprise intelligence brief format):
  category              — topic category token, e.g. "FOUNDATION MODELS"
  update_block          — full narrative prose under "THE UPDATE" (required)
  strategic_implications — full narrative prose under "STRATEGIC IMPLICATIONS" (optional)

Every article that passes filters and dedup will have a SummaryResult
generated by one of: Groq → Mistral → OpenRouter → Gemini → Raw.

SECURITY: __repr__ never exposes content longer than 50 chars.
          This prevents API response content appearing in logs.
"""

from dataclasses import dataclass
from typing import Optional


@dataclass
class SummaryResult:
    """
    Structured intelligence brief summary of a news article.

    Fields populated by parser (from LLM response or raw fallback):
        category               — topic category, ALL CAPS (e.g. "FOUNDATION MODELS")
        update_block           — narrative prose: what happened and why (required)
        strategic_implications — narrative prose: so-what for AI builders (optional)

    Fields set by summarizer:
        llm_provider      — which provider generated this ('groq', 'mistral',
                            'openrouter_llama', 'openrouter_mistral', 'gemini', 'raw')
        used_raw_fallback — True only when no LLM succeeded
    """

    category: str
    update_block: str
    strategic_implications: str
    llm_provider: str = "unknown"
    used_raw_fallback: bool = False

    def __repr__(self) -> str:
        """
        Safe repr — truncates content fields to 50 chars.
        Prevents LLM response content from appearing in logs.
        """
        def _trunc(s: str, n: int = 50) -> str:
            if not s:
                return "''"
            return repr(s[:n] + ("..." if len(s) > n else ""))

        return (
            f"SummaryResult("
            f"provider={self.llm_provider!r}, "
            f"raw={self.used_raw_fallback}, "
            f"category={self.category!r}, "
            f"update={_trunc(self.update_block)}"
            f")"
        )
