"""
orchestrator/models/summary.py
--------------------------------
SummaryResult dataclass — the canonical output of the LLM fallback chain.

Every article that passes filters and dedup will have a SummaryResult
generated by one of: Groq → Mistral → OpenRouter → Gemini → Raw.

SECURITY: __repr__ never exposes content longer than 50 chars.
          This prevents API response content appearing in logs.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class SummaryResult:
    """
    Structured LLM summary of a news article.

    Fields populated by parser (from LLM response or raw fallback):
        headline    — ALL CAPS headline, max 15 words
        paragraph_1 — What happened, who involved (required)
        paragraph_2 — Why it matters, scale (optional)
        paragraph_3 — Context, reactions, what's next (optional)
        point_1     — The exact event (optional)
        point_2     — How it happened (optional)
        point_3     — Who is affected (optional)
        point_4     — Scale or numbers — None if no data available
        point_5     — Key quote or reaction (optional)
        conclusion  — 1-2 sentence so-what (optional)

    Fields set by summarizer:
        llm_provider    — which provider generated this ('groq', 'mistral',
                          'openrouter_llama', 'openrouter_mistral',
                          'gemini', 'raw')
        used_raw_fallback — True only when no LLM succeeded
    """

    headline: str
    paragraph_1: str
    paragraph_2: str
    paragraph_3: str
    point_1: str
    point_2: str
    point_3: str
    point_4: Optional[str]   # None when no quantitative data available
    point_5: str
    conclusion: str
    llm_provider: str = "unknown"
    used_raw_fallback: bool = False

    def __repr__(self) -> str:
        """
        Safe repr — truncates all content fields to 50 chars.
        Prevents LLM response content from appearing in logs.
        """
        def _trunc(s: str, n: int = 50) -> str:
            if not s:
                return "''"
            return repr(s[:n] + ("..." if len(s) > n else ""))

        return (
            f"SummaryResult("
            f"provider={self.llm_provider!r}, "
            f"raw={self.used_raw_fallback}, "
            f"headline={_trunc(self.headline)}, "
            f"p1={_trunc(self.paragraph_1)}"
            f")"
        )
